version: "3.8"
services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - "${MYSQLDB_PUBLIC_PORT}:${MYSQLDB_CONTAINER_PORT}"
    volumes:
      - db:/var/lib/mysql
    networks:
      - appnetwork
  backend:
    depends_on:
      - mysqldb
    restart: on-failure
    env_file: ./.env
    image: anas129/backend:latest
    ports:
      - "${SPRING_PUBLIC_PORT}:${SPRING_CONTAINER_PORT}"
    environment:
      SPRING_APPLICATION_JSON: '{
          "spring.datasource.url"  : "jdbc:mysql://mysqldb:$MYSQLDB_CONTAINER_PORT/$MYSQLDB_DATABASE?useSSL=false",
          "spring.datasource.username" : "$MYSQLDB_USER",
          "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
          "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
          "spring.jpa.hibernate.ddl-auto" : "update"
        }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
    networks:
      - appnetwork
  frontend:
    depends_on:
      - backend
    restart: on-failure
    image: anas129/frontend:latest
    ports:
      - "${ANGULAR_PUBLIC_PORT}:${ANGULAR_CONTAINER_PORT}"
    networks:
      - appnetwork
volumes:
  db:
networks:
  appnetwork:
    driver: bridge